version: "3.9"
services:
  db:
    image: postgres:16
    container_name: diagramforge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: diagramforge
      POSTGRES_USER: diagram
      POSTGRES_PASSWORD: secret
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diagram -d diagramforge"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
